FROM registry.access.redhat.com/ubi9/ubi:latest

# install cosign
ENV COSIGN_VERSION=2.2.0
RUN curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-${COSIGN_VERSION}.x86_64.rpm" && \
    yum install -y cosign-${COSIGN_VERSION}.x86_64.rpm

# install rekor-cli
RUN curl -O -L "https://github.com/sigstore/rekor/releases/latest/download/rekor-cli-linux-amd64" && \
    mv rekor-cli-linux-amd64 /usr/local/bin/rekor-cli && \
    chmod 755 /usr/local/bin/rekor-cli

# install podman
RUN yum install -y podman

# install crane
RUN curl -O -L "https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz" && \
    tar -xsf go-containerregistry_Linux_x86_64.tar.gz -C /usr/local/bin/ crane

CMD ["sleep","100000"]
