---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: tssc
  labels:
    app: tssc-terminal
    app.kubernetes.io/component: tssc
    app.kubernetes.io/instance: tssc
    app.kubernetes.io/name: tssc
    app.kubernetes.io/part-of: tssc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tssc
  template:
    metadata:
      labels:
        app: tssc
    spec:
      serviceAccountName: tssc
      serviceAccount: tssc
      containers:
        - name: demo-app
          image: quay.io/smileyfritz/tssc-terminal:v0.1.11
          env:
          - name: "XDG_RUNTIME_DIR"
            value: "~/.config"
          - name: "REGISTRY_AUTH_FILE"
            value: "~/.config/containers/auth.json"
          securityContext:
            privileged: true
